-- MySQL Script generated by MySQL Workbench
-- qua 10 out 2018 15:00:06 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `idItem` INT NOT NULL,
  `Itemcol` INT NOT NULL,
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uf` (
  `idUf` INT NOT NULL,
  `Ufcol` CHAR(2) NOT NULL,
  PRIMARY KEY (`idUf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `Departamentocol` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mes` (
  `idmes` INT NOT NULL,
  `mescol` DATE NOT NULL,
  PRIMARY KEY (`idmes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `idVendas` INT NOT NULL,
  `Vendascol` INT NOT NULL,
  `fk_Item` INT NULL,
  `fk_Departamento` INT NULL,
  `fk_Uf` INT NULL,
  `fk_Mes` INT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `fk_Vendas_1_idx` (`fk_Item` ASC),
  INDEX `fk_Vendas_2_idx` (`fk_Departamento` ASC),
  INDEX `fk_Vendas_3_idx` (`fk_Uf` ASC),
  INDEX `fk_Vendas_4_idx` (`fk_Mes` ASC),
  CONSTRAINT `fk_Vendas_1`
    FOREIGN KEY (`fk_Item`)
    REFERENCES `mydb`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_2`
    FOREIGN KEY (`fk_Departamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_3`
    FOREIGN KEY (`fk_Uf`)
    REFERENCES `mydb`.`Uf` (`idUf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendas_4`
    FOREIGN KEY (`fk_Mes`)
    REFERENCES `mydb`.`Mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visitas` (
  `idVisitas` INT NOT NULL,
  `Visitascol` INT NOT NULL,
  `fk_Departamento` INT NULL,
  `fk_Item` INT NULL,
  `fk_Uf` INT NULL,
  `fk_Mes` INT NULL,
  PRIMARY KEY (`idVisitas`),
  INDEX `fk_Visitas_1_idx` (`fk_Departamento` ASC),
  INDEX `fk_Visitas_2_idx` (`fk_Item` ASC),
  INDEX `fk_Visitas_3_idx` (`fk_Uf` ASC),
  INDEX `fk_Visitas_4_idx` (`fk_Mes` ASC),
  CONSTRAINT `fk_Visitas_1`
    FOREIGN KEY (`fk_Departamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitas_2`
    FOREIGN KEY (`fk_Item`)
    REFERENCES `mydb`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitas_3`
    FOREIGN KEY (`fk_Uf`)
    REFERENCES `mydb`.`Uf` (`idUf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitas_4`
    FOREIGN KEY (`fk_Mes`)
    REFERENCES `mydb`.`Mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Financeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Financeiro` (
  `idFinanceiro` INT NOT NULL,
  `Faturamento_Produto` DOUBLE NULL,
  `Faturamento_Frete` FLOAT NULL,
  `Custo_Produto` FLOAT NULL,
  `Custo_Frete` FLOAT NULL,
  `Custo_Mkt` FLOAT NULL,
  `Desconto_Produto` FLOAT NULL,
  `Desconto_Frete` FLOAT NULL,
  `fk_Departamento` INT NULL,
  `fk_Item` INT NULL,
  `fk_Mes` INT NULL,
  `fk_Uf` INT NULL,
  PRIMARY KEY (`idFinanceiro`),
  INDEX `fk_Financeiro_1_idx` (`fk_Departamento` ASC),
  INDEX `fk_Financeiro_2_idx` (`fk_Item` ASC),
  INDEX `fk_Financeiro_3_idx` (`fk_Mes` ASC),
  INDEX `fk_Financeiro_4_idx` (`fk_Uf` ASC),
  CONSTRAINT `fk_Financeiro_1`
    FOREIGN KEY (`fk_Departamento`)
    REFERENCES `mydb`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financeiro_2`
    FOREIGN KEY (`fk_Item`)
    REFERENCES `mydb`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financeiro_3`
    FOREIGN KEY (`fk_Mes`)
    REFERENCES `mydb`.`Mes` (`idmes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Financeiro_4`
    FOREIGN KEY (`fk_Uf`)
    REFERENCES `mydb`.`Uf` (`idUf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
